### PR TITLE
Add link to the presigned POST object properties

### PR DESCRIPTION
**Pull request by wparad**
(Making a new PR since it was incorrectly closed it #28).

> Thank you for your pull request. That link is already been added to earlier on the page. Please reopen the pull request if you disagree
@panjws 

No this link isn't anywhere on the page: https://docs.aws.amazon.com/AmazonS3/latest/userguide/PresignedUrlUploadObject.html

The list of properties allowed/enabled for presigned POSTs is always impossible to find. The default location linked to must contain a link to this documentation. If there's a suggestion on how better to link to this content, I'm all ears!

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by panjws** [comment]
Its right here:  "You can generate a presigned URL programmatically using the REST API, .NET, AWS SDK for Java, Ruby, AWS SDK for JavaScript, PHP, , and Python. " The REST API link points to the requested page. Please retry and confirm,

**Comment by wparad** [comment]
Okay wow, I missed that because it totally doesn't make sense in that section. The text reads:

> You can generate a presigned URL...using the REST API

Which is 100% untrue, you can't generate the URL using the REST API because the URL is generated 100% client side using the v4 algorithm. Also the use of the REST API to upload the result is required irrespective of the tool you use to generate the URL. I suggest along with my change to remove the `REST API` text and link since that page doesn't actually tell you how to generate the presigned url.

**Comment by aws-alan** [comment]
Closing due to age.

**Comment by wparad** [comment]
why was this closed, the problem still exists. What do I need to do to get this fixed.

**Pull request closed without merging**
