### PR TITLE
note that first run of S3 lifecycle rules can take 48 hours

### PR DESCRIPTION
**Pull request by fsiler**
*Issue #, if available:*

*Description of changes:*
note that new lifecycle rules can take 48 hours before first run.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by fsiler** [comment]
Hi, wondered about expected timeline of this being merged or the docs otherwise being fixed.

**Comment by fsiler** [comment]
Is there any plan to merge these changes?

**Comment by aws-alan** [comment]
Hello,

Thank you for your feedback. Amazon S3 does not offer a 48-hour SLA (Service Level Agreement) for new Lifecycle rules and therefore we cannot add language this firm. 

Thanks.

**Comment by fsiler** [comment]
I'm not asking you to suggest an SLA.  I'm saying that you need to point out a *limitation* that it may take 48 hours, because these things aren't anywhere near instantaneous in the typical experience.

**Pull request closed without merging**
