### PR TITLE
Update privatelink-interface-endpoints.md

### PR DESCRIPTION
**Pull request by ifaqeer-zz**
Added for clarity. Self-explanatory.

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by sasake615** [comment]
Thank you for your pull request! A member of the team will review it and will provide updates here about progress.

**Comment by sasake615** [comment]
Thanks again for your suggestion. If you would, please make two minor adjustments as shown below and I can merge your pull request:
> With AWS PrivateLink for Amazon S3, you can provision *interface VPC endpoints* \(interface endpoints\) in your virtual private cloud \(VPC\) instead of connecting over the internet\. These endpoints are directly accessible from applications that are on premises (over VPN and AWS Direct Connect) or in a different AWS Region (over VPC peering)\.

**Comment by ifaqeer-zz** [comment]
> With AWS PrivateLink for Amazon S3, you can provision interface VPC endpoints (interface endpoints) in your virtual private cloud (VPC) instead of connecting over the internet. These endpoints are directly accessible from applications that are on premises (over VPN and AWS Direct Connect) or in a different AWS Region (over VPC peering).

I hope that this is what you mean by make two minor adjustments? Thanks

**Comment by sasake615** [comment]
Hi! Yes please. If you would, please add 'AWS' in front of 'Direct Connect' and lowercase the letter 'p' in 'peering' in another commit on the same branch. That should update the pull request and then I can merge it. Thanks so much.

**Comment by ifaqeer-zz** [comment]
>  in another commit on the same branch

Sorry, but don't know how to do above.

**Comment by sasake615** [comment]
Hope it is OK that I made the changes. Merging your pull request.

**Pull request merged**
